AyeCode/userswp

includes/class-emails.php

https://userswp.io/support/topic/translation-of-login-in-email/

Translation of login in email - FIXED

---

includes/class-forms.php
includes/class-templates.php

registration redirect - FIXED

---

admin/settings/class-formbuilder.php
includes/class-profile.php
includes/class-templates.php
includes/class-userswp.php
includes/helpers/fields.php
includes/helpers/misc.php
includes/libraries/class-geodirectory-plugin.php
includes/libraries/index.php
public/assets/css/partials/_profile.scss
public/assets/css/users-wp.css
readme.txt

See https://userswp.io/support/topic/form-builder-custom-icon/

Icon url in custom field icon does not working - FIXED

---

includes/class-forms.php
readme.txt

Fix conflict with Google Captcha plugin. - FIXED

---

includes/helpers/misc.php

Remove edit banner and avatar image from user profile in backend.

---

includes/helpers/misc.php

fix issue with pagination for users listing

---

includes/class-forms.php
templates/login.php

after login it should redirect to prev page - FIXED

---

includes/class-ajax.php
includes/class-emails.php
includes/class-forms.php
includes/class-pages.php
includes/class-profile.php
includes/class-templates.php
includes/helpers/misc.php
includes/helpers/pages.php
includes/helpers/permalinks.php
includes/libraries/class-geodirectory-plugin.php
readme.txt

CHanges for WPML compatibility

Test with WPML - FIXED

---

includes/class-profile.php
includes/helpers/misc.php

Edit user backend page issues - FIXED

---

includes/libraries/class-geodirectory-plugin.php
readme.txt

See: https://wpgeodirectory.com/support/topic/members-page/page/2/#post-418378

Fix reviews displaying for deleted listings.

---

includes/class-forms.php
includes/class-meta.php
includes/class-userswp.php
readme.txt

Add Resend Activation Email for users - ADDED

---

includes/class-forms.php
readme.txt

For https://userswp.io/support/topic/reset-password-issues/#post-1659

Add hook to modify the content of forgot password email.

---

includes/class-meta.php
includes/class-userswp.php
readme.txt

Delete user meta on removing from site of multisite network - FIXED

---

includes/libraries/class-geodirectory-plugin.php
readme.txt

Change text domain from "uwp-gd' to "userswp" for few strings in the class-geodirectory-plugin.php file.
Also, Provide hooks and filters to display other data for listings in UWP profile tabs.

Change text domain in class-geodirectory-plugin.php file

---

includes/class-import-export.php
includes/class-shortcodes.php
readme.txt

Styling on Permalink Registration Page vs. Shortcode Page - FIXED

---

admin/settings/class-settings.php
includes/class-forms.php
readme.txt

Provided a hook so that users can force redirect users to registration redirect page or custom page after successful registration.

Filter to force redirect after registration

---

includes/class-profile.php
includes/libraries/class-geodirectory-plugin.php
readme.txt

Reviews tab using gravatar when comments are using UsersWP profile - FIXED

---

includes/class-forms.php

Fix - https://userswp.io/support/topic/translation-missing-on-registration-with-confirmation

Fix translation issue of the string.

---

includes/class-profile.php
includes/libraries/class-geodirectory-plugin.php
readme.txt

Default avatar showing next to review instead of listing featured image - FIXED

---

includes/libraries/class-geodirectory-plugin.php
readme.txt

Listing Type Tab Order as CPT Order - FIXED

---

admin/settings/class-settings.php
readme.txt

Tab Re-order - FIXED

---

admin/settings/class-settings.php
includes/class-import-export.php
includes/class-tables.php
includes/class-userswp.php
includes/class-validation.php
includes/helpers/forms.php
readme.txt

Remove password field from the account fields

---

includes/class-callback.php
includes/class-emails.php
includes/class-files.php
includes/class-forms.php
includes/class-profile.php
includes/class-user-notifications.php
includes/class-userswp.php
includes/helpers/tabs.php
includes/libraries/class-geodirectory-plugin.php
includes/libraries/class-invoicing-plugin.php
readme.txt
uninstall.php

Fixes #231 , Fixes #234 , Fixes #233 , Fixes #232 , Fixes #176

GDV2 compatibility changes

---

admin/settings/admin-settings-ie-users.php
includes/class-forms.php
includes/class-import-export.php
includes/class-validation.php
readme.txt
vendor/ayecode/wp-font-awesome-settings/wp-font-awesome-settings.php
vendor/ayecode/wp-super-duper/wp-super-duper.php
vendor/composer/installed.json

updated FA settings library

---

includes/class-profile.php
readme.txt

See https://userswp.io/support/topic/page-change-password-is-blank-privacy-settings-do-not-work/

Field privacy setting "Let User Decide" is not working - FIXED

---

includes/class-forms.php
includes/class-validation.php
includes/helpers/forms.php
includes/helpers/misc.php
includes/libraries/class-geodirectory-plugin.php
readme.txt

Oxygen editor compatibility added

---

includes/class-validation.php

Fix issues posted on git.

---

admin/class-admin-setup-wizard.php
includes/helpers/forms.php
readme.txt

Allow to enable registration from setup wizard if disable in WP settings

---

admin/class-admin.php
admin/class-uwp-admin-menus.php
admin/settings/class-formbuilder.php
admin/settings/class-uwp-settings-general.php
admin/views/html-admin-page-status.php
includes/class-addons.php
includes/class-forms.php
includes/class-tools.php
includes/class-userswp.php
includes/class-validation.php
includes/helpers/misc.php
readme.txt

added user role field and tools menu as a submenu

---

admin/class-admin-setup-wizard.php
includes/class-userswp.php
includes/helpers/misc.php
includes/helpers/tabs.php
templates/bootstrap/search-form.php

setup wizard changes for enabling multisite registration

---

admin/class-admin.php
admin/settings/class-formbuilder.php
includes/class-profile.php
includes/libraries/class-geodirectory-plugin.php
readme.txt
templates/bootstrap/posts-post.php

Fixes #503 , Fixes #501, Fixes #488

Remove profile tabs if content is empty for GeoDirectory

---

admin/settings/class-formbuilder.php
admin/settings/functions.php
includes/class-forms.php
includes/libraries/class-geodirectory-plugin.php
readme.txt
templates/bootstrap/comments-item.php

fixed GDPR and TOC fields visibility issue in register form builder

---

includes/class-meta.php
includes/class-userswp.php
includes/class-uwp-seo.php

fixed some of issues on git

---

includes/class-emails.php
includes/class-userswp.php
readme.txt
vendor/ayecode/wp-ayecode-ui/ayecode-ui-loader.php
vendor/ayecode/wp-ayecode-ui/change-log.txt
vendor/ayecode/wp-ayecode-ui/includes/ayecode-ui-settings.php
vendor/ayecode/wp-ayecode-ui/includes/class-aui.php
vendor/ayecode/wp-ayecode-ui/includes/components/class-aui-component-input.php
vendor/ayecode/wp-super-duper/change-log.txt
vendor/ayecode/wp-super-duper/sd-functions.php
vendor/ayecode/wp-super-duper/wp-super-duper.php
vendor/composer/InstalledVersions.php
vendor/composer/autoload_files.php
vendor/composer/autoload_static.php
vendor/composer/installed.json
vendor/composer/installed.php

updated AUI and SD

---

includes/class-activator.php

fix undefined index error

---

includes/libraries/class-geodirectory-plugin.php
readme.txt

Added filter to allow displaying all reviews with or without ratings

---

includes/libraries/class-geodirectory-plugin.php
readme.txt

added filter to edit listings tab query parameter

---

admin/class-admin.php
admin/settings/class-formbuilder.php
admin/settings/class-uwp-settings-redirects.php
includes/class-activator.php
includes/helpers/forms.php
readme.txt
widgets/register.php

added functionality to show register form using 'user_type' query args

---

includes/class-files.php
includes/class-user-notifications.php
readme.txt

Fix notification disabling not working issue and include image.php file

---

includes/class-uwp-compatibility.php
readme.txt

Elementor compatibility error on Events demo site import - FIXED

---

admin/settings/class-uwp-settings-page.php

Email settings show/hide advanced button fix

---

admin/settings/class-uwp-settings-user-sorting.php
includes/class-forms.php
includes/helpers/misc.php
readme.txt
widgets/user-badge.php
widgets/user-meta.php

Single quote in slect field label, required/validation message shows unwanted backslash - FIXED

---

includes/class-templates.php
templates/bootstrap/register.php
templates/register.php

Make registration form submit button and `redirect_to` hookable  
- Added a hook to customize the submit button.  
- Made the `redirect_to` parameter filterable.

Make registration form submit button and  hookable

---

includes/class-templates.php
readme.txt

added frontend body class for the user type
